# Configurable Logo Used for CartoDB export
APPLICATION_LOGO_URL: 'http://geoblacklight.org/images/geoblacklight-logo.png'

#BING_SITE_VERIFICATION: '4E61263975C6ABBF2ECE5A8CA5E592B7'

# Carto OneClick Service https://carto.com/engine/open-in-carto/
CARTO_ONECLICK_LINK: 'http://oneclick.carto.com/'

# ArcGIS Online Base URL
ARCGIS_BASE_URL: 'https://www.arcgis.com/home/webmap/viewer.html'

# Download path can be configured using this setting
#DOWNLOAD_PATH: "./tmp/cache/downloads"

EMAIL_TO: 'fake-email@example.com'

# The bq boost value for spatial search matches within a bounding box
BBOX_WITHIN_BOOST: '50'

# The bf boost value for overlap ratio
OVERLAP_RATIO_BOOST: '10'

# Homepage Map Geometry
# Leave null to default to entire world
# Add a stringified GeoJSON object to scope initial render (example from UMass)
HOMEPAGE_MAP_GEOM: null
# HOMEPAGE_MAP_GEOM: '{"type":"Polygon","coordinates":[[[-73.58,42.93],[-73.58,41.20],[-69.90,41.20],[-69.90,42.93]]]}'

# Non-search-field GeoBlacklight application permitted params
GBL_PARAMS:
  - :bbox
  - :email
  - :file
  - :format
  - :id
  - :logo
  - :provider
  - :type
  - :BBOX
  - :HEIGHT
  - :LAYERS
  - :QUERY_LAYERS
  - :URL
  - :WIDTH
  - :X
  - :Y

# Solr field mappings
FIELDS:
  :ACCESS_RIGHTS: 'dct_accessRights_s'
  :ALTERNATIVE_TITLE: 'dct_alternative_sm'
  :CENTROID: 'dcat_centroid'
  :CREATOR: 'dct_creator_sm'
  :DATE_ISSUED: 'dct_issued_s'
  :DATE_RANGE: 'gbl_dateRange_drsim'
  :DESCRIPTION: 'dct_description_sm'
  :DISPLAY_NOTE: 'gbl_displayNote_sm'
  :FORMAT: 'dct_format_s'
  :FILE_SIZE: 'gbl_fileSize_s'
  :GEOREFERENCED: 'gbl_georeferenced_b'
  :ID: 'id'
  :IDENTIFIER: 'dct_identifier_sm'
  :INDEX_YEAR: 'gbl_indexYear_im'
  :IS_PART_OF: 'dct_isPartOf_sm'
  :IS_REPLACED_BY: 'dct_isReplacedBy_sm'
  :THEME: 'dcat_theme_sm'
  :KEYWORD: 'dcat_keyword_sm'
  :LANGUAGE: 'dct_language_sm'
  :LAYER_MODIFED: 'gbl_mdModified_dt'
  :LICENSE: 'dct_license_sm'
  :MEMBER_OF: 'pcdm_memberOf_sm'
  :METADATA_VERSION: 'gbl_mdVersion_s'
  :MODIFIED: 'gbl_mdModified_dt'
  :OVERLAP_FIELD: 'solr_bboxtype'
  :PUBLISHER: 'dct_publisher_sm'
  :PROVIDER: 'schema_provider_s'
  :REFERENCES: 'dct_references_s'
  :RELATION: 'dct_relation_sm'
  :REPLACES: 'dct_replaces_sm'
  :RESOURCE_CLASS: 'gbl_resourceClass_sm'
  :RESOURCE_TYPE: 'gbl_resourceType_sm'
  :RIGHTS: 'dct_rights_sm'
  :RIGHTS_HOLDER: 'dct_rightsHolder_sm'
  :SOURCE: 'dct_source_sm'
  :SPATIAL_COVERAGE: 'dct_spatial_sm'
  :GEOMETRY: 'locn_geometry'
  :SUBJECT: 'dct_subject_sm'
  :SUPPRESSED: 'gbl_suppressed_b'
  :TEMPORAL_COVERAGE: 'dct_temporal_sm'
  :TITLE: 'dct_title_s'
  :VERSION: 'dct_isVersionOf_sm'
  :WXS_IDENTIFIER: 'gbl_wxsIdentifier_s'
  # B1G Custom Fields Geoportal / GEOMG
  :B1G_ACCESS: 'b1g_access_s'
  :B1G_DATE_ACCESSIONED: 'b1g_dateAccessioned_sm'
  :B1G_ACCRUAL_METHOD: 'b1g_dct_accrualMethod_s'
  :B1G_CHILD_RECORD: 'b1g_child_record_b'
  :B1G_CODE: 'b1g_code_s'
  :B1G_DATE_CREATED: 'date_created_dtsi'
  :B1G_GEOMG_ID: 'geomg_id_s'
  :B1G_GEOREFERENCED_ALLMAPS: 'b1g_georeferenced_allmaps_b'
  :B1G_IMAGE: 'b1g_image_ss'
  :B1G_LANGUAGE: 'b1g_language_sm'
  :B1G_MEDIATOR: 'b1g_dct_mediator_sm'
  :B1G_PUBLICATION_STATE: 'b1g_publication_state_s'
  :B1G_IMPORT_ID: 'b1g_geom_import_id_ssi'

GEOMONITOR_TOLERANCE: 0.8
#GOOGLE_ANALYTICS_ID: 'UA-XXXXX-X'
#GOOGLE_SITE_VERIFICATION: 'I1DQ46tUnPOrYpnhDUsy5tOL22oywWb2LyUTwT8M-HU'
HOSTNAME: 'HOST'
HOST_URL: 'http://geo.btaa.org'
INSTITUTION: 'University of Minnesota'

INSTITUTION_LOCAL_NAME: 'Minnesota'
INSTITUTION_GEOSERVER_URL: 'https://geoserver.princeton.edu'
PROXY_GEOSERVER_URL: 'http://localhost:3000'
PROXY_GEOSERVER_AUTH: 'Basic base64encodedusername:password'

GBLSI_THUMBNAIL_FIELD: 'b1g_image_ss'

# Metadata shown in tool panel
METADATA_SHOWN:
  - 'fgdc'
  - 'iso19139'
  - 'mods'
  - 'html'

# Display Notes to display / Non-prefixed default bootstrap class is alert-secondary
DISPLAY_NOTES_SHOWN:
  danger:
    bootstrap_alert_class: alert-danger
    icon: fire-solid
    note_prefix: "Danger: "
  info:
    bootstrap_alert_class: alert-info
    icon: circle-info-solid
    note_prefix: "Info: "
  tip:
    bootstrap_alert_class: alert-success
    icon: lightbulb-solid
    note_prefix: "Tip: "
  warning:
    bootstrap_alert_class: alert-warning
    icon: triangle-exclamation-solid
    note_prefix: "Warning: "

#NEWRELIC_APP_NAME: 'should be specific to stage and prod'
#NEWRELIC_LICENSE_KEY: 'this is private'

PROXY_URL: 'http://www.example.com/restricted'

RESTRICTED_URL: 'http://www.example-services.com'

#SQUASH_API_HOST: 'http://squash-host.example.com'
#SQUASH_API_KEY: 'squash-api-key'
#SQUASH_DISABLE: <%= (Rails.env.development? || Rails.env.test?) %>

# (For external Download) timeout and open_timeout parameters for Faraday
TIMEOUT_DOWNLOAD: 16

# (For WMS inspection) timeout and open_timeout parameters for Faraday
TIMEOUT_WMS: 4

# Use the geometry type for the data relations icon
USE_GEOM_FOR_RELATIONS_ICON: false

# Web services shown in tool panel
WEBSERVICES_SHOWN:
  - 'wms'
  - 'tms'
  - 'wfs'
  - 'xyz'
  - 'wmts'
  - 'tilejson'
  - 'iiif'
  - 'feature_layer'
  - 'tiled_map_layer'
  - 'dynamic_map_layer'
  - 'image_map_layer'
  - 'cog'
  - 'pmtiles'

# Relationships to display
RELATIONSHIPS_SHOWN:
  MEMBER_OF_ANCESTORS:
    field: pcdm_memberOf_sm
    icon: parent-item
    inverse: :MEMBER_OF_DESCENDANTS
    label: geoblacklight.relations.member_of_ancestors
    query_type: ancestors
  MEMBER_OF_DESCENDANTS:
    field: pcdm_memberOf_sm
    icon: child-item
    inverse: :MEMBER_OF_ANCESTORS
    label: geoblacklight.relations.member_of_descendants
    query_type: descendants
  PART_OF_ANCESTORS:
    field: dct_isPartOf_sm
    icon: parent-item
    inverse: :PART_OF_DESCENDANTS
    label: geoblacklight.relations.part_of_ancestors
    query_type: ancestors
  PART_OF_DESCENDANTS:
    field: dct_isPartOf_sm
    icon: child-item
    inverse: :PART_OF_ANCESTORS
    label: geoblacklight.relations.part_of_descendants
    query_type: descendants
  RELATION_ANCESTORS:
    field: dct_relation_sm
    icon: nil
    inverse: :RELATION_DESCENDANTS
    label: geoblacklight.relations.relation_ancestors
    query_type: ancestors
  RELATION_DESCENDANTS:
    field: dct_relation_sm
    icon: nil
    inverse: :RELATION_ANCESTORS
    label: geoblacklight.relations.relation_descendants
    query_type: descendants
  REPLACES_ANCESTORS:
    field: dct_replaces_sm
    icon: nil
    inverse: :REPLACES_DESCENDANTS
    label: geoblacklight.relations.replaces_ancestors
    query_type: ancestors
  REPLACES_DESCENDANTS:
    field: dct_replaces_sm
    icon: nil
    inverse: :REPLACES_ANCESTORS
    label: geoblacklight.relations.replaces_descendants
    query_type: descendants
  SOURCE_ANCESTORS:
    field: dct_source_sm
    icon: parent-item
    inverse: :SOURCE_DESCENDANTS
    label: geoblacklight.relations.source_ancestors
    query_type: ancestors
  SOURCE_DESCENDANTS:
    field: dct_source_sm
    icon: child-item
    inverse: :SOURCE_ANCESTORS
    label: geoblacklight.relations.source_descendants
    query_type: descendants
  VERSION_OF_ANCESTORS:
    field: dct_isVersionOf_sm
    icon: parent-item
    inverse: :VERSION_OF_DESCENDANTS
    label: geoblacklight.relations.version_of_ancestors
    query_type: ancestors
  VERSION_OF_DESCENDANTS:
    field: dct_isVersionOf_sm
    icon: child-item
    inverse: :VERSION_OF_ANCESTORS
    label: geoblacklight.relations.version_of_descendants
    query_type: descendants

WMS_PARAMS:
  :SERVICE: 'WMS'
  :VERSION: '1.1.1'
  :REQUEST: 'GetFeatureInfo'
  :STYLES: ''
  :SRS: 'EPSG:4326'
  :EXCEPTIONS: 'application/json'
  :INFO_FORMAT: 'text/html'

# Settings for leaflet
OPACITY_CONTROL: &opacity_control
  CONTROLS:
    - 'Opacity'

LEAFLET:
  MAP:
  LAYERS:
    DETECT_RETINA: true
    INDEX:
      DEFAULT: &default
        color: "#1eb300"
        weight: "1"
        radius: "4"
      UNAVAILABLE:
        <<: *default
        color: "#b3001e"
      SELECTED:
        <<: *default
        color: "#006bde"
  VIEWERS:
    DOWNLOAD:
      CONTROLS:
    DYNAMICMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    FEATURELAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    IIIF:
      CONTROLS:
        - 'Fullscreen'
    IMAGEMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    INDEXMAP:
      CONTROLS:
        - 'Fullscreen'
    WMS:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    TILEDMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'

# Toggle the help text feature that offers users context
HELP_TEXT:
  viewer_protocol:
      - 'b1g_image'
      - 'cog'
      - 'download'
      - 'dynamic_map_layer'
      - 'feature_layer'
      - 'iiif'
      - 'iiif_manifest'
      - 'image_map_layer'
      - 'index_map'
      - 'oembed'
      - 'pmtiles'
      - 'tiled_map_layer'
      - 'tilejson'
      - 'tms'
      - 'wms'
      - 'wmts'
      - 'xyz'

# Enable catalog#show sidebar static map for items with the following viewer protocols
SIDEBAR_STATIC_MAP:
  - 'b1g_image'
  - 'download'
  - 'iiif'
  - 'iiif_manifest'
  - 'map'

#########
# GBL ADMIN SETTINGS

# Used to generate derivatives in app/uploaders/asset_uploader.rb
# Hash of thumbnail sizes
GBL_ADMIN_THUMBNAIL_WIDTHS:
  mini: 50
  standard: 200